[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "cross-origin"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/canvaskit/*"
  [headers.values]
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cross-Origin-Resource-Policy = "cross-origin"
